// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.4
// source: proto/probe_sync.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataType 数据类型枚举
type DataType int32

const (
	DataType_DATA_TYPE_UNSPECIFIED DataType = 0
	DataType_DATA_TYPE_ACCESS_LOGS DataType = 1
	DataType_DATA_TYPE_ALERTS      DataType = 2
	DataType_DATA_TYPE_DECISIONS   DataType = 3
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "DATA_TYPE_UNSPECIFIED",
		1: "DATA_TYPE_ACCESS_LOGS",
		2: "DATA_TYPE_ALERTS",
		3: "DATA_TYPE_DECISIONS",
	}
	DataType_value = map[string]int32{
		"DATA_TYPE_UNSPECIFIED": 0,
		"DATA_TYPE_ACCESS_LOGS": 1,
		"DATA_TYPE_ALERTS":      2,
		"DATA_TYPE_DECISIONS":   3,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_probe_sync_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_proto_probe_sync_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_proto_probe_sync_proto_rawDescGZIP(), []int{0}
}

// CommandStatus 指令执行状态
type CommandStatus int32

const (
	CommandStatus_COMMAND_STATUS_UNSPECIFIED CommandStatus = 0
	CommandStatus_COMMAND_STATUS_SUCCESS     CommandStatus = 1
	CommandStatus_COMMAND_STATUS_FAILED      CommandStatus = 2
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "COMMAND_STATUS_UNSPECIFIED",
		1: "COMMAND_STATUS_SUCCESS",
		2: "COMMAND_STATUS_FAILED",
	}
	CommandStatus_value = map[string]int32{
		"COMMAND_STATUS_UNSPECIFIED": 0,
		"COMMAND_STATUS_SUCCESS":     1,
		"COMMAND_STATUS_FAILED":      2,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_probe_sync_proto_enumTypes[1].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_proto_probe_sync_proto_enumTypes[1]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_probe_sync_proto_rawDescGZIP(), []int{1}
}

// AckStatus 确认状态枚举
type AckStatus int32

const (
	AckStatus_ACK_STATUS_UNSPECIFIED AckStatus = 0
	AckStatus_ACK_STATUS_OK          AckStatus = 1
	AckStatus_ACK_STATUS_DUPLICATE   AckStatus = 2 // 幂等：重复 batch_id
	AckStatus_ACK_STATUS_ERROR       AckStatus = 3
)

// Enum value maps for AckStatus.
var (
	AckStatus_name = map[int32]string{
		0: "ACK_STATUS_UNSPECIFIED",
		1: "ACK_STATUS_OK",
		2: "ACK_STATUS_DUPLICATE",
		3: "ACK_STATUS_ERROR",
	}
	AckStatus_value = map[string]int32{
		"ACK_STATUS_UNSPECIFIED": 0,
		"ACK_STATUS_OK":          1,
		"ACK_STATUS_DUPLICATE":   2,
		"ACK_STATUS_ERROR":       3,
	}
)

func (x AckStatus) Enum() *AckStatus {
	p := new(AckStatus)
	*p = x
	return p
}

func (x AckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_probe_sync_proto_enumTypes[2].Descriptor()
}

func (AckStatus) Type() protoreflect.EnumType {
	return &file_proto_probe_sync_proto_enumTypes[2]
}

func (x AckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckStatus.Descriptor instead.
func (AckStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_probe_sync_proto_rawDescGZIP(), []int{2}
}

// CommandType 指令类型枚举
type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED      CommandType = 0
	CommandType_COMMAND_TYPE_PING             CommandType = 1
	CommandType_COMMAND_TYPE_FORCE_SYNC       CommandType = 2
	CommandType_COMMAND_TYPE_ADD_WHITELIST    CommandType = 3
	CommandType_COMMAND_TYPE_REMOVE_WHITELIST CommandType = 4
	CommandType_COMMAND_TYPE_ADD_DECISION     CommandType = 5
	CommandType_COMMAND_TYPE_REMOVE_DECISION  CommandType = 6
	CommandType_COMMAND_TYPE_UPDATE_CONFIG    CommandType = 7
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_TYPE_PING",
		2: "COMMAND_TYPE_FORCE_SYNC",
		3: "COMMAND_TYPE_ADD_WHITELIST",
		4: "COMMAND_TYPE_REMOVE_WHITELIST",
		5: "COMMAND_TYPE_ADD_DECISION",
		6: "COMMAND_TYPE_REMOVE_DECISION",
		7: "COMMAND_TYPE_UPDATE_CONFIG",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":      0,
		"COMMAND_TYPE_PING":             1,
		"COMMAND_TYPE_FORCE_SYNC":       2,
		"COMMAND_TYPE_ADD_WHITELIST":    3,
		"COMMAND_TYPE_REMOVE_WHITELIST": 4,
		"COMMAND_TYPE_ADD_DECISION":     5,
		"COMMAND_TYPE_REMOVE_DECISION":  6,
		"COMMAND_TYPE_UPDATE_CONFIG":    7,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_probe_sync_proto_enumTypes[3].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_proto_probe_sync_proto_enumTypes[3]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_probe_sync_proto_rawDescGZIP(), []int{3}
}

// ProbeMessage 探针发送的消息
type ProbeMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ProbeId string                 `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProbeMessage_Heartbeat
	//	*ProbeMessage_DataBatch
	//	*ProbeMessage_CommandAck
	Payload       isProbeMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeMessage) Reset() {
	*x = ProbeMessage{}
	mi := &file_proto_probe_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeMessage) ProtoMessage() {}

func (x *ProbeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeMessage.ProtoReflect.Descriptor instead.
func (*ProbeMessage) Descriptor() ([]byte, []int) {
	return file_proto_probe_sync_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeMessage) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *ProbeMessage) GetPayload() isProbeMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProbeMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ProbeMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ProbeMessage) GetDataBatch() *DataBatch {
	if x != nil {
		if x, ok := x.Payload.(*ProbeMessage_DataBatch); ok {
			return x.DataBatch
		}
	}
	return nil
}

func (x *ProbeMessage) GetCommandAck() *CommandAck {
	if x != nil {
		if x, ok := x.Payload.(*ProbeMessage_CommandAck); ok {
			return x.CommandAck
		}
	}
	return nil
}

type isProbeMessage_Payload interface {
	isProbeMessage_Payload()
}

type ProbeMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,10,opt,name=heartbeat,proto3,oneof"`
}

type ProbeMessage_DataBatch struct {
	DataBatch *DataBatch `protobuf:"bytes,11,opt,name=data_batch,json=dataBatch,proto3,oneof"`
}

type ProbeMessage_CommandAck struct {
	CommandAck *CommandAck `protobuf:"bytes,12,opt,name=command_ack,json=commandAck,proto3,oneof"`
}

func (*ProbeMessage_Heartbeat) isProbeMessage_Payload() {}

func (*ProbeMessage_DataBatch) isProbeMessage_Payload() {}

func (*ProbeMessage_CommandAck) isProbeMessage_Payload() {}

// Heartbeat 心跳消息
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        *ProbeStatus           `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_probe_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_probe_sync_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Heartbeat) GetStatus() *ProbeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// ProbeStatus 探针状态
type ProbeStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Version           string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds     int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	PendingAccessLogs int64                  `protobuf:"varint,3,opt,name=pending_access_logs,json=pendingAccessLogs,proto3" json:"pending_access_logs,omitempty"`
	PendingAlerts     int64                  `protobuf:"varint,4,opt,name=pending_alerts,json=pendingAlerts,proto3" json:"pending_alerts,omitempty"`
	PendingDecisions  int64                  `protobuf:"varint,5,opt,name=pending_decisions,json=pendingDecisions,proto3" json:"pending_decisions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProbeStatus) Reset() {
	*x = ProbeStatus{}
	mi := &file_proto_probe_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeStatus) ProtoMessage() {}

func (x *ProbeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeStatus.ProtoReflect.Descriptor instead.
func (*ProbeStatus) Descriptor() ([]byte, []int) {
	return file_proto_probe_sync_proto_rawDescGZIP(), []int{2}
}

func (x *ProbeStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProbeStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ProbeStatus) GetPendingAccessLogs() int64 {
	if x != nil {
		return x.PendingAccessLogs
	}
	return 0
}

func (x *ProbeStatus) GetPendingAlerts() int64 {
	if x != nil {
		return x.PendingAlerts
	}
	return 0
}

func (x *ProbeStatus) GetPendingDecisions() int64 {
	if x != nil {
		return x.PendingDecisions
	}
	return 0
}

// DataBatch 数据批次
type DataBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"` // 幂等键: {probe_id}-{type}-{from}-{to}
	Type          DataType               `protobuf:"varint,2,opt,name=type,proto3,enum=probesync.DataType" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON 编码的数据数组
	CursorFrom    int64                  `protobuf:"varint,4,opt,name=cursor_from,json=cursorFrom,proto3" json:"cursor_from,omitempty"`
	CursorTo      int64                  `protobuf:"varint,5,opt,name=cursor_to,json=cursorTo,proto3" json:"cursor_to,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataBatch) Reset() {
	*x = DataBatch{}
	mi := &file_proto_probe_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBatch) ProtoMessage() {}

func (x *DataBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBatch.ProtoReflect.Descriptor instead.
func (*DataBatch) Descriptor() ([]byte, []int) {
	return file_proto_probe_sync_proto_rawDescGZIP(), []int{3}
}

func (x *DataBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *DataBatch) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *DataBatch) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataBatch) GetCursorFrom() int64 {
	if x != nil {
		return x.CursorFrom
	}
	return 0
}

func (x *DataBatch) GetCursorTo() int64 {
	if x != nil {
		return x.CursorTo
	}
	return 0
}

func (x *DataBatch) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// CommandAck 指令执行确认
type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        CommandStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=probesync.CommandStatus" json:"status,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // JSON 编码的结果
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_proto_probe_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_proto_probe_sync_proto_rawDescGZIP(), []int{4}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_COMMAND_STATUS_UNSPECIFIED
}

func (x *CommandAck) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CommandAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// BackendMessage 后端发送的消息
type BackendMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BackendMessage_HeartbeatAck
	//	*BackendMessage_BatchAck
	//	*BackendMessage_Command
	//	*BackendMessage_ConfigUpdate
	Payload       isBackendMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendMessage) Reset() {
	*x = BackendMessage{}
	mi := &file_proto_probe_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendMessage) ProtoMessage() {}

func (x *BackendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendMessage.ProtoReflect.Descriptor instead.
func (*BackendMessage) Descriptor() ([]byte, []int) {
	return file_proto_probe_sync_proto_rawDescGZIP(), []int{5}
}

func (x *BackendMessage) GetPayload() isBackendMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BackendMessage) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*BackendMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *BackendMessage) GetBatchAck() *BatchAck {
	if x != nil {
		if x, ok := x.Payload.(*BackendMessage_BatchAck); ok {
			return x.BatchAck
		}
	}
	return nil
}

func (x *BackendMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*BackendMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *BackendMessage) GetConfigUpdate() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Payload.(*BackendMessage_ConfigUpdate); ok {
			return x.ConfigUpdate
		}
	}
	return nil
}

type isBackendMessage_Payload interface {
	isBackendMessage_Payload()
}

type BackendMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,10,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type BackendMessage_BatchAck struct {
	BatchAck *BatchAck `protobuf:"bytes,11,opt,name=batch_ack,json=batchAck,proto3,oneof"`
}

type BackendMessage_Command struct {
	Command *Command `protobuf:"bytes,12,opt,name=command,proto3,oneof"`
}

type BackendMessage_ConfigUpdate struct {
	ConfigUpdate *ConfigUpdate `protobuf:"bytes,13,opt,name=config_update,json=configUpdate,proto3,oneof"`
}

func (*BackendMessage_HeartbeatAck) isBackendMessage_Payload() {}

func (*BackendMessage_BatchAck) isBackendMessage_Payload() {}

func (*BackendMessage_Command) isBackendMessage_Payload() {}

func (*BackendMessage_ConfigUpdate) isBackendMessage_Payload() {}

// HeartbeatAck 心跳响应
type HeartbeatAck struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ServerTime            string                 `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	ConfigUpdateAvailable bool                   `protobuf:"varint,2,opt,name=config_update_available,json=configUpdateAvailable,proto3" json:"config_update_available,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_proto_probe_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_proto_probe_sync_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatAck) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

func (x *HeartbeatAck) GetConfigUpdateAvailable() bool {
	if x != nil {
		return x.ConfigUpdateAvailable
	}
	return false
}

// BatchAck 批次确认
type BatchAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Status        AckStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=probesync.AckStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAck) Reset() {
	*x = BatchAck{}
	mi := &file_proto_probe_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAck) ProtoMessage() {}

func (x *BatchAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAck.ProtoReflect.Descriptor instead.
func (*BatchAck) Descriptor() ([]byte, []int) {
	return file_proto_probe_sync_proto_rawDescGZIP(), []int{7}
}

func (x *BatchAck) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchAck) GetStatus() AckStatus {
	if x != nil {
		return x.Status
	}
	return AckStatus_ACK_STATUS_UNSPECIFIED
}

func (x *BatchAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Command 指令消息
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=probesync.CommandType" json:"type,omitempty"`
	Params        []byte                 `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"` // JSON 编码的参数
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_probe_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_probe_sync_proto_rawDescGZIP(), []int{8}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *Command) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Command) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Command) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

// ConfigUpdate 配置更新
type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Config        []byte                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"` // YAML 配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_proto_probe_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_proto_probe_sync_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigUpdate) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigUpdate) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_proto_probe_sync_proto protoreflect.FileDescriptor

const file_proto_probe_sync_proto_rawDesc = "" +
	"\n" +
	"\x16proto/probe_sync.proto\x12\tprobesync\"\xdb\x01\n" +
	"\fProbeMessage\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\tR\aprobeId\x124\n" +
	"\theartbeat\x18\n" +
	" \x01(\v2\x14.probesync.HeartbeatH\x00R\theartbeat\x125\n" +
	"\n" +
	"data_batch\x18\v \x01(\v2\x14.probesync.DataBatchH\x00R\tdataBatch\x128\n" +
	"\vcommand_ack\x18\f \x01(\v2\x15.probesync.CommandAckH\x00R\n" +
	"commandAckB\t\n" +
	"\apayload\"Y\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12.\n" +
	"\x06status\x18\x02 \x01(\v2\x16.probesync.ProbeStatusR\x06status\"\xd2\x01\n" +
	"\vProbeStatus\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12.\n" +
	"\x13pending_access_logs\x18\x03 \x01(\x03R\x11pendingAccessLogs\x12%\n" +
	"\x0epending_alerts\x18\x04 \x01(\x03R\rpendingAlerts\x12+\n" +
	"\x11pending_decisions\x18\x05 \x01(\x03R\x10pendingDecisions\"\xbf\x01\n" +
	"\tDataBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.probesync.DataTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1f\n" +
	"\vcursor_from\x18\x04 \x01(\x03R\n" +
	"cursorFrom\x12\x1b\n" +
	"\tcursor_to\x18\x05 \x01(\x03R\bcursorTo\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"\x8b\x01\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.probesync.CommandStatusR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xff\x01\n" +
	"\x0eBackendMessage\x12>\n" +
	"\rheartbeat_ack\x18\n" +
	" \x01(\v2\x17.probesync.HeartbeatAckH\x00R\fheartbeatAck\x122\n" +
	"\tbatch_ack\x18\v \x01(\v2\x13.probesync.BatchAckH\x00R\bbatchAck\x12.\n" +
	"\acommand\x18\f \x01(\v2\x12.probesync.CommandH\x00R\acommand\x12>\n" +
	"\rconfig_update\x18\r \x01(\v2\x17.probesync.ConfigUpdateH\x00R\fconfigUpdateB\t\n" +
	"\apayload\"g\n" +
	"\fHeartbeatAck\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\tR\n" +
	"serverTime\x126\n" +
	"\x17config_update_available\x18\x02 \x01(\bR\x15configUpdateAvailable\"i\n" +
	"\bBatchAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.probesync.AckStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x9b\x01\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.probesync.CommandTypeR\x04type\x12\x16\n" +
	"\x06params\x18\x03 \x01(\fR\x06params\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\tR\texpiresAt\"@\n" +
	"\fConfigUpdate\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06config\x18\x02 \x01(\fR\x06config*o\n" +
	"\bDataType\x12\x19\n" +
	"\x15DATA_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DATA_TYPE_ACCESS_LOGS\x10\x01\x12\x14\n" +
	"\x10DATA_TYPE_ALERTS\x10\x02\x12\x17\n" +
	"\x13DATA_TYPE_DECISIONS\x10\x03*f\n" +
	"\rCommandStatus\x12\x1e\n" +
	"\x1aCOMMAND_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16COMMAND_STATUS_SUCCESS\x10\x01\x12\x19\n" +
	"\x15COMMAND_STATUS_FAILED\x10\x02*j\n" +
	"\tAckStatus\x12\x1a\n" +
	"\x16ACK_STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACK_STATUS_OK\x10\x01\x12\x18\n" +
	"\x14ACK_STATUS_DUPLICATE\x10\x02\x12\x14\n" +
	"\x10ACK_STATUS_ERROR\x10\x03*\x83\x02\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11COMMAND_TYPE_PING\x10\x01\x12\x1b\n" +
	"\x17COMMAND_TYPE_FORCE_SYNC\x10\x02\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_ADD_WHITELIST\x10\x03\x12!\n" +
	"\x1dCOMMAND_TYPE_REMOVE_WHITELIST\x10\x04\x12\x1d\n" +
	"\x19COMMAND_TYPE_ADD_DECISION\x10\x05\x12 \n" +
	"\x1cCOMMAND_TYPE_REMOVE_DECISION\x10\x06\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_UPDATE_CONFIG\x10\a2N\n" +
	"\tProbeSync\x12A\n" +
	"\aConnect\x12\x17.probesync.ProbeMessage\x1a\x19.probesync.BackendMessage(\x010\x01B4Z2github.com/crowdsecurity/crowdsec/pkg/probesync/pbb\x06proto3"

var (
	file_proto_probe_sync_proto_rawDescOnce sync.Once
	file_proto_probe_sync_proto_rawDescData []byte
)

func file_proto_probe_sync_proto_rawDescGZIP() []byte {
	file_proto_probe_sync_proto_rawDescOnce.Do(func() {
		file_proto_probe_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_probe_sync_proto_rawDesc), len(file_proto_probe_sync_proto_rawDesc)))
	})
	return file_proto_probe_sync_proto_rawDescData
}

var file_proto_probe_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_probe_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_probe_sync_proto_goTypes = []any{
	(DataType)(0),          // 0: probesync.DataType
	(CommandStatus)(0),     // 1: probesync.CommandStatus
	(AckStatus)(0),         // 2: probesync.AckStatus
	(CommandType)(0),       // 3: probesync.CommandType
	(*ProbeMessage)(nil),   // 4: probesync.ProbeMessage
	(*Heartbeat)(nil),      // 5: probesync.Heartbeat
	(*ProbeStatus)(nil),    // 6: probesync.ProbeStatus
	(*DataBatch)(nil),      // 7: probesync.DataBatch
	(*CommandAck)(nil),     // 8: probesync.CommandAck
	(*BackendMessage)(nil), // 9: probesync.BackendMessage
	(*HeartbeatAck)(nil),   // 10: probesync.HeartbeatAck
	(*BatchAck)(nil),       // 11: probesync.BatchAck
	(*Command)(nil),        // 12: probesync.Command
	(*ConfigUpdate)(nil),   // 13: probesync.ConfigUpdate
}
var file_proto_probe_sync_proto_depIdxs = []int32{
	5,  // 0: probesync.ProbeMessage.heartbeat:type_name -> probesync.Heartbeat
	7,  // 1: probesync.ProbeMessage.data_batch:type_name -> probesync.DataBatch
	8,  // 2: probesync.ProbeMessage.command_ack:type_name -> probesync.CommandAck
	6,  // 3: probesync.Heartbeat.status:type_name -> probesync.ProbeStatus
	0,  // 4: probesync.DataBatch.type:type_name -> probesync.DataType
	1,  // 5: probesync.CommandAck.status:type_name -> probesync.CommandStatus
	10, // 6: probesync.BackendMessage.heartbeat_ack:type_name -> probesync.HeartbeatAck
	11, // 7: probesync.BackendMessage.batch_ack:type_name -> probesync.BatchAck
	12, // 8: probesync.BackendMessage.command:type_name -> probesync.Command
	13, // 9: probesync.BackendMessage.config_update:type_name -> probesync.ConfigUpdate
	2,  // 10: probesync.BatchAck.status:type_name -> probesync.AckStatus
	3,  // 11: probesync.Command.type:type_name -> probesync.CommandType
	4,  // 12: probesync.ProbeSync.Connect:input_type -> probesync.ProbeMessage
	9,  // 13: probesync.ProbeSync.Connect:output_type -> probesync.BackendMessage
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_probe_sync_proto_init() }
func file_proto_probe_sync_proto_init() {
	if File_proto_probe_sync_proto != nil {
		return
	}
	file_proto_probe_sync_proto_msgTypes[0].OneofWrappers = []any{
		(*ProbeMessage_Heartbeat)(nil),
		(*ProbeMessage_DataBatch)(nil),
		(*ProbeMessage_CommandAck)(nil),
	}
	file_proto_probe_sync_proto_msgTypes[5].OneofWrappers = []any{
		(*BackendMessage_HeartbeatAck)(nil),
		(*BackendMessage_BatchAck)(nil),
		(*BackendMessage_Command)(nil),
		(*BackendMessage_ConfigUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_probe_sync_proto_rawDesc), len(file_proto_probe_sync_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_probe_sync_proto_goTypes,
		DependencyIndexes: file_proto_probe_sync_proto_depIdxs,
		EnumInfos:         file_proto_probe_sync_proto_enumTypes,
		MessageInfos:      file_proto_probe_sync_proto_msgTypes,
	}.Build()
	File_proto_probe_sync_proto = out.File
	file_proto_probe_sync_proto_goTypes = nil
	file_proto_probe_sync_proto_depIdxs = nil
}
