// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.4
// source: probe_sync.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandStatus 指令执行状态
type CommandStatus int32

const (
	CommandStatus_COMMAND_STATUS_UNSPECIFIED CommandStatus = 0
	CommandStatus_COMMAND_STATUS_SUCCESS     CommandStatus = 1
	CommandStatus_COMMAND_STATUS_FAILED      CommandStatus = 2
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "COMMAND_STATUS_UNSPECIFIED",
		1: "COMMAND_STATUS_SUCCESS",
		2: "COMMAND_STATUS_FAILED",
	}
	CommandStatus_value = map[string]int32{
		"COMMAND_STATUS_UNSPECIFIED": 0,
		"COMMAND_STATUS_SUCCESS":     1,
		"COMMAND_STATUS_FAILED":      2,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_probe_sync_proto_enumTypes[0].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_probe_sync_proto_enumTypes[0]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{0}
}

// AckStatus 确认状态枚举
type AckStatus int32

const (
	AckStatus_ACK_STATUS_UNSPECIFIED AckStatus = 0
	AckStatus_ACK_STATUS_OK          AckStatus = 1
	AckStatus_ACK_STATUS_DUPLICATE   AckStatus = 2 // 幂等：重复 batch_id
	AckStatus_ACK_STATUS_ERROR       AckStatus = 3
)

// Enum value maps for AckStatus.
var (
	AckStatus_name = map[int32]string{
		0: "ACK_STATUS_UNSPECIFIED",
		1: "ACK_STATUS_OK",
		2: "ACK_STATUS_DUPLICATE",
		3: "ACK_STATUS_ERROR",
	}
	AckStatus_value = map[string]int32{
		"ACK_STATUS_UNSPECIFIED": 0,
		"ACK_STATUS_OK":          1,
		"ACK_STATUS_DUPLICATE":   2,
		"ACK_STATUS_ERROR":       3,
	}
)

func (x AckStatus) Enum() *AckStatus {
	p := new(AckStatus)
	*p = x
	return p
}

func (x AckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_probe_sync_proto_enumTypes[1].Descriptor()
}

func (AckStatus) Type() protoreflect.EnumType {
	return &file_probe_sync_proto_enumTypes[1]
}

func (x AckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckStatus.Descriptor instead.
func (AckStatus) EnumDescriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{1}
}

// CommandType 指令类型枚举
type CommandType int32

const (
	COMMAND_TYPE_UNSPECIFIED           CommandType = 0
	COMMAND_TYPE_PING                  CommandType = 1
	COMMAND_TYPE_FORCE_SYNC            CommandType = 2
	COMMAND_TYPE_ADD_WHITELIST         CommandType = 3
	COMMAND_TYPE_REMOVE_WHITELIST      CommandType = 4
	COMMAND_TYPE_ADD_DECISION          CommandType = 5
	COMMAND_TYPE_REMOVE_DECISION       CommandType = 6
	COMMAND_TYPE_UPDATE_CONFIG         CommandType = 7
	COMMAND_TYPE_HOST_LOCK_PATH        CommandType = 8
	COMMAND_TYPE_HOST_TEMP_UNLOCK_PATH CommandType = 9
	COMMAND_TYPE_HOST_EMERGENCY_UNLOCK CommandType = 10
	COMMAND_TYPE_HOST_QUERY_STATUS     CommandType = 11
	COMMAND_TYPE_HOST_APPLY_POLICY     CommandType = 12
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0:  "COMMAND_TYPE_UNSPECIFIED",
		1:  "COMMAND_TYPE_PING",
		2:  "COMMAND_TYPE_FORCE_SYNC",
		3:  "COMMAND_TYPE_ADD_WHITELIST",
		4:  "COMMAND_TYPE_REMOVE_WHITELIST",
		5:  "COMMAND_TYPE_ADD_DECISION",
		6:  "COMMAND_TYPE_REMOVE_DECISION",
		7:  "COMMAND_TYPE_UPDATE_CONFIG",
		8:  "COMMAND_TYPE_HOST_LOCK_PATH",
		9:  "COMMAND_TYPE_HOST_TEMP_UNLOCK_PATH",
		10: "COMMAND_TYPE_HOST_EMERGENCY_UNLOCK",
		11: "COMMAND_TYPE_HOST_QUERY_STATUS",
		12: "COMMAND_TYPE_HOST_APPLY_POLICY",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":           0,
		"COMMAND_TYPE_PING":                  1,
		"COMMAND_TYPE_FORCE_SYNC":            2,
		"COMMAND_TYPE_ADD_WHITELIST":         3,
		"COMMAND_TYPE_REMOVE_WHITELIST":      4,
		"COMMAND_TYPE_ADD_DECISION":          5,
		"COMMAND_TYPE_REMOVE_DECISION":       6,
		"COMMAND_TYPE_UPDATE_CONFIG":         7,
		"COMMAND_TYPE_HOST_LOCK_PATH":        8,
		"COMMAND_TYPE_HOST_TEMP_UNLOCK_PATH": 9,
		"COMMAND_TYPE_HOST_EMERGENCY_UNLOCK": 10,
		"COMMAND_TYPE_HOST_QUERY_STATUS":     11,
		"COMMAND_TYPE_HOST_APPLY_POLICY":     12,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_probe_sync_proto_enumTypes[2].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_probe_sync_proto_enumTypes[2]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{2}
}

// ProbeMessage 探针发送的消息
type ProbeMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ProbeId string                 `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProbeMessage_Heartbeat
	//	*ProbeMessage_DataBatch
	//	*ProbeMessage_CommandAck
	Payload       isProbeMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeMessage) Reset() {
	*x = ProbeMessage{}
	mi := &file_probe_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeMessage) ProtoMessage() {}

func (x *ProbeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeMessage.ProtoReflect.Descriptor instead.
func (*ProbeMessage) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeMessage) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *ProbeMessage) GetPayload() isProbeMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProbeMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ProbeMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ProbeMessage) GetDataBatch() *DataBatch {
	if x != nil {
		if x, ok := x.Payload.(*ProbeMessage_DataBatch); ok {
			return x.DataBatch
		}
	}
	return nil
}

func (x *ProbeMessage) GetCommandAck() *CommandAck {
	if x != nil {
		if x, ok := x.Payload.(*ProbeMessage_CommandAck); ok {
			return x.CommandAck
		}
	}
	return nil
}

type isProbeMessage_Payload interface {
	isProbeMessage_Payload()
}

type ProbeMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,10,opt,name=heartbeat,proto3,oneof"`
}

type ProbeMessage_DataBatch struct {
	DataBatch *DataBatch `protobuf:"bytes,11,opt,name=data_batch,json=dataBatch,proto3,oneof"`
}

type ProbeMessage_CommandAck struct {
	CommandAck *CommandAck `protobuf:"bytes,12,opt,name=command_ack,json=commandAck,proto3,oneof"`
}

func (*ProbeMessage_Heartbeat) isProbeMessage_Payload() {}

func (*ProbeMessage_DataBatch) isProbeMessage_Payload() {}

func (*ProbeMessage_CommandAck) isProbeMessage_Payload() {}

// Heartbeat 心跳消息
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        *ProbeStatus           `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_probe_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Heartbeat) GetStatus() *ProbeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// ProbeStatus 探针状态
type ProbeStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Version           string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds     int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	PendingAccessLogs int64                  `protobuf:"varint,3,opt,name=pending_access_logs,json=pendingAccessLogs,proto3" json:"pending_access_logs,omitempty"`
	PendingAlerts     int64                  `protobuf:"varint,4,opt,name=pending_alerts,json=pendingAlerts,proto3" json:"pending_alerts,omitempty"`
	PendingDecisions  int64                  `protobuf:"varint,5,opt,name=pending_decisions,json=pendingDecisions,proto3" json:"pending_decisions,omitempty"`
	PendingHostLogs   int64                  `protobuf:"varint,6,opt,name=pending_host_logs,json=pendingHostLogs,proto3" json:"pending_host_logs,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProbeStatus) Reset() {
	*x = ProbeStatus{}
	mi := &file_probe_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeStatus) ProtoMessage() {}

func (x *ProbeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeStatus.ProtoReflect.Descriptor instead.
func (*ProbeStatus) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{2}
}

func (x *ProbeStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProbeStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ProbeStatus) GetPendingAccessLogs() int64 {
	if x != nil {
		return x.PendingAccessLogs
	}
	return 0
}

func (x *ProbeStatus) GetPendingAlerts() int64 {
	if x != nil {
		return x.PendingAlerts
	}
	return 0
}

func (x *ProbeStatus) GetPendingDecisions() int64 {
	if x != nil {
		return x.PendingDecisions
	}
	return 0
}

func (x *ProbeStatus) GetPendingHostLogs() int64 {
	if x != nil {
		return x.PendingHostLogs
	}
	return 0
}

// DataBatch 数据批次
type DataBatch struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	BatchId    string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"` // 幂等键: {probe_id}-{payload}-{from}-{to}
	CursorFrom int64                  `protobuf:"varint,4,opt,name=cursor_from,json=cursorFrom,proto3" json:"cursor_from,omitempty"`
	CursorTo   int64                  `protobuf:"varint,5,opt,name=cursor_to,json=cursorTo,proto3" json:"cursor_to,omitempty"`
	Timestamp  string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DataBatch_CaddyLogs
	//	*DataBatch_Alerts
	//	*DataBatch_Decisions
	//	*DataBatch_HostActivityLogs
	//	*DataBatch_HostProtectionLogs
	Payload       isDataBatch_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataBatch) Reset() {
	*x = DataBatch{}
	mi := &file_probe_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBatch) ProtoMessage() {}

func (x *DataBatch) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBatch.ProtoReflect.Descriptor instead.
func (*DataBatch) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{3}
}

func (x *DataBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *DataBatch) GetCursorFrom() int64 {
	if x != nil {
		return x.CursorFrom
	}
	return 0
}

func (x *DataBatch) GetCursorTo() int64 {
	if x != nil {
		return x.CursorTo
	}
	return 0
}

func (x *DataBatch) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *DataBatch) GetPayload() isDataBatch_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataBatch) GetCaddyLogs() *CaddyLogBatch {
	if x != nil {
		if x, ok := x.Payload.(*DataBatch_CaddyLogs); ok {
			return x.CaddyLogs
		}
	}
	return nil
}

func (x *DataBatch) GetAlerts() *AlertBatch {
	if x != nil {
		if x, ok := x.Payload.(*DataBatch_Alerts); ok {
			return x.Alerts
		}
	}
	return nil
}

func (x *DataBatch) GetDecisions() *DecisionBatch {
	if x != nil {
		if x, ok := x.Payload.(*DataBatch_Decisions); ok {
			return x.Decisions
		}
	}
	return nil
}

func (x *DataBatch) GetHostActivityLogs() *HostActivityLogBatch {
	if x != nil {
		if x, ok := x.Payload.(*DataBatch_HostActivityLogs); ok {
			return x.HostActivityLogs
		}
	}
	return nil
}

func (x *DataBatch) GetHostProtectionLogs() *HostProtectionLogBatch {
	if x != nil {
		if x, ok := x.Payload.(*DataBatch_HostProtectionLogs); ok {
			return x.HostProtectionLogs
		}
	}
	return nil
}

type isDataBatch_Payload interface {
	isDataBatch_Payload()
}

type DataBatch_CaddyLogs struct {
	CaddyLogs *CaddyLogBatch `protobuf:"bytes,10,opt,name=caddy_logs,json=caddyLogs,proto3,oneof"`
}

type DataBatch_Alerts struct {
	Alerts *AlertBatch `protobuf:"bytes,11,opt,name=alerts,proto3,oneof"`
}

type DataBatch_Decisions struct {
	Decisions *DecisionBatch `protobuf:"bytes,12,opt,name=decisions,proto3,oneof"`
}

type DataBatch_HostActivityLogs struct {
	HostActivityLogs *HostActivityLogBatch `protobuf:"bytes,13,opt,name=host_activity_logs,json=hostActivityLogs,proto3,oneof"`
}

type DataBatch_HostProtectionLogs struct {
	HostProtectionLogs *HostProtectionLogBatch `protobuf:"bytes,14,opt,name=host_protection_logs,json=hostProtectionLogs,proto3,oneof"`
}

func (*DataBatch_CaddyLogs) isDataBatch_Payload() {}

func (*DataBatch_Alerts) isDataBatch_Payload() {}

func (*DataBatch_Decisions) isDataBatch_Payload() {}

func (*DataBatch_HostActivityLogs) isDataBatch_Payload() {}

func (*DataBatch_HostProtectionLogs) isDataBatch_Payload() {}

// CaddyLogBatch 访问日志批次
type CaddyLogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CaddyLog            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaddyLogBatch) Reset() {
	*x = CaddyLogBatch{}
	mi := &file_probe_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaddyLogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaddyLogBatch) ProtoMessage() {}

func (x *CaddyLogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaddyLogBatch.ProtoReflect.Descriptor instead.
func (*CaddyLogBatch) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{4}
}

func (x *CaddyLogBatch) GetItems() []*CaddyLog {
	if x != nil {
		return x.Items
	}
	return nil
}

// CaddyLog Caddy 访问日志结构
type CaddyLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Ts            float64                `protobuf:"fixed64,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Logger        string                 `protobuf:"bytes,3,opt,name=logger,proto3" json:"logger,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Request       *CaddyRequest          `protobuf:"bytes,5,opt,name=request,proto3" json:"request,omitempty"`
	BytesRead     int64                  `protobuf:"varint,6,opt,name=bytes_read,json=bytesRead,proto3" json:"bytes_read,omitempty"`
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Duration      float64                `protobuf:"fixed64,8,opt,name=duration,proto3" json:"duration,omitempty"`
	Size          int64                  `protobuf:"varint,9,opt,name=size,proto3" json:"size,omitempty"`
	Status        uint32                 `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	RespHeaders   map[string]*StringList `protobuf:"bytes,11,rep,name=resp_headers,json=respHeaders,proto3" json:"resp_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaddyLog) Reset() {
	*x = CaddyLog{}
	mi := &file_probe_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaddyLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaddyLog) ProtoMessage() {}

func (x *CaddyLog) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaddyLog.ProtoReflect.Descriptor instead.
func (*CaddyLog) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{5}
}

func (x *CaddyLog) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *CaddyLog) GetTs() float64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *CaddyLog) GetLogger() string {
	if x != nil {
		return x.Logger
	}
	return ""
}

func (x *CaddyLog) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CaddyLog) GetRequest() *CaddyRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CaddyLog) GetBytesRead() int64 {
	if x != nil {
		return x.BytesRead
	}
	return 0
}

func (x *CaddyLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CaddyLog) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CaddyLog) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CaddyLog) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CaddyLog) GetRespHeaders() map[string]*StringList {
	if x != nil {
		return x.RespHeaders
	}
	return nil
}

// CaddyRequest 请求详情
type CaddyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteIp      string                 `protobuf:"bytes,1,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	RemotePort    string                 `protobuf:"bytes,2,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	ClientIp      string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Proto         string                 `protobuf:"bytes,4,opt,name=proto,proto3" json:"proto,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Host          string                 `protobuf:"bytes,6,opt,name=host,proto3" json:"host,omitempty"`
	Uri           string                 `protobuf:"bytes,7,opt,name=uri,proto3" json:"uri,omitempty"`
	Headers       map[string]*StringList `protobuf:"bytes,8,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tls           *CaddyTls              `protobuf:"bytes,9,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaddyRequest) Reset() {
	*x = CaddyRequest{}
	mi := &file_probe_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaddyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaddyRequest) ProtoMessage() {}

func (x *CaddyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaddyRequest.ProtoReflect.Descriptor instead.
func (*CaddyRequest) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{6}
}

func (x *CaddyRequest) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

func (x *CaddyRequest) GetRemotePort() string {
	if x != nil {
		return x.RemotePort
	}
	return ""
}

func (x *CaddyRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *CaddyRequest) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *CaddyRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CaddyRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CaddyRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *CaddyRequest) GetHeaders() map[string]*StringList {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CaddyRequest) GetTls() *CaddyTls {
	if x != nil {
		return x.Tls
	}
	return nil
}

// CaddyTls TLS 信息
type CaddyTls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resumed       bool                   `protobuf:"varint,1,opt,name=resumed,proto3" json:"resumed,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	CipherSuite   uint32                 `protobuf:"varint,3,opt,name=cipher_suite,json=cipherSuite,proto3" json:"cipher_suite,omitempty"`
	Proto         string                 `protobuf:"bytes,4,opt,name=proto,proto3" json:"proto,omitempty"`
	ServerName    string                 `protobuf:"bytes,5,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaddyTls) Reset() {
	*x = CaddyTls{}
	mi := &file_probe_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaddyTls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaddyTls) ProtoMessage() {}

func (x *CaddyTls) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaddyTls.ProtoReflect.Descriptor instead.
func (*CaddyTls) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{7}
}

func (x *CaddyTls) GetResumed() bool {
	if x != nil {
		return x.Resumed
	}
	return false
}

func (x *CaddyTls) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CaddyTls) GetCipherSuite() uint32 {
	if x != nil {
		return x.CipherSuite
	}
	return 0
}

func (x *CaddyTls) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *CaddyTls) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

// StringList 字符串列表
type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_probe_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{8}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// AlertBatch 告警批次
type AlertBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Alert               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertBatch) Reset() {
	*x = AlertBatch{}
	mi := &file_probe_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertBatch) ProtoMessage() {}

func (x *AlertBatch) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertBatch.ProtoReflect.Descriptor instead.
func (*AlertBatch) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{9}
}

func (x *AlertBatch) GetItems() []*Alert {
	if x != nil {
		return x.Items
	}
	return nil
}

// Alert 告警结构
type Alert struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Scenario        string                 `protobuf:"bytes,4,opt,name=scenario,proto3" json:"scenario,omitempty"`
	BucketId        string                 `protobuf:"bytes,5,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	Message         string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	EventsCount     int32                  `protobuf:"varint,7,opt,name=events_count,json=eventsCount,proto3" json:"events_count,omitempty"`
	StartedAt       string                 `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	StoppedAt       string                 `protobuf:"bytes,9,opt,name=stopped_at,json=stoppedAt,proto3" json:"stopped_at,omitempty"`
	SourceIp        string                 `protobuf:"bytes,10,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SourceRange     string                 `protobuf:"bytes,11,opt,name=source_range,json=sourceRange,proto3" json:"source_range,omitempty"`
	SourceAsNumber  string                 `protobuf:"bytes,12,opt,name=source_as_number,json=sourceAsNumber,proto3" json:"source_as_number,omitempty"`
	SourceAsName    string                 `protobuf:"bytes,13,opt,name=source_as_name,json=sourceAsName,proto3" json:"source_as_name,omitempty"`
	SourceCountry   string                 `protobuf:"bytes,14,opt,name=source_country,json=sourceCountry,proto3" json:"source_country,omitempty"`
	SourceLatitude  float64                `protobuf:"fixed64,15,opt,name=source_latitude,json=sourceLatitude,proto3" json:"source_latitude,omitempty"`
	SourceLongitude float64                `protobuf:"fixed64,16,opt,name=source_longitude,json=sourceLongitude,proto3" json:"source_longitude,omitempty"`
	SourceScope     string                 `protobuf:"bytes,17,opt,name=source_scope,json=sourceScope,proto3" json:"source_scope,omitempty"`
	SourceValue     string                 `protobuf:"bytes,18,opt,name=source_value,json=sourceValue,proto3" json:"source_value,omitempty"`
	Capacity        int32                  `protobuf:"varint,19,opt,name=capacity,proto3" json:"capacity,omitempty"`
	LeakSpeed       string                 `protobuf:"bytes,20,opt,name=leak_speed,json=leakSpeed,proto3" json:"leak_speed,omitempty"`
	ScenarioVersion string                 `protobuf:"bytes,21,opt,name=scenario_version,json=scenarioVersion,proto3" json:"scenario_version,omitempty"`
	ScenarioHash    string                 `protobuf:"bytes,22,opt,name=scenario_hash,json=scenarioHash,proto3" json:"scenario_hash,omitempty"`
	Simulated       bool                   `protobuf:"varint,23,opt,name=simulated,proto3" json:"simulated,omitempty"`
	Uuid            string                 `protobuf:"bytes,24,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Remediation     bool                   `protobuf:"varint,25,opt,name=remediation,proto3" json:"remediation,omitempty"`
	MachineAlerts   int64                  `protobuf:"varint,26,opt,name=machine_alerts,json=machineAlerts,proto3" json:"machine_alerts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_probe_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{10}
}

func (x *Alert) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Alert) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Alert) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Alert) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *Alert) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetEventsCount() int32 {
	if x != nil {
		return x.EventsCount
	}
	return 0
}

func (x *Alert) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Alert) GetStoppedAt() string {
	if x != nil {
		return x.StoppedAt
	}
	return ""
}

func (x *Alert) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *Alert) GetSourceRange() string {
	if x != nil {
		return x.SourceRange
	}
	return ""
}

func (x *Alert) GetSourceAsNumber() string {
	if x != nil {
		return x.SourceAsNumber
	}
	return ""
}

func (x *Alert) GetSourceAsName() string {
	if x != nil {
		return x.SourceAsName
	}
	return ""
}

func (x *Alert) GetSourceCountry() string {
	if x != nil {
		return x.SourceCountry
	}
	return ""
}

func (x *Alert) GetSourceLatitude() float64 {
	if x != nil {
		return x.SourceLatitude
	}
	return 0
}

func (x *Alert) GetSourceLongitude() float64 {
	if x != nil {
		return x.SourceLongitude
	}
	return 0
}

func (x *Alert) GetSourceScope() string {
	if x != nil {
		return x.SourceScope
	}
	return ""
}

func (x *Alert) GetSourceValue() string {
	if x != nil {
		return x.SourceValue
	}
	return ""
}

func (x *Alert) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Alert) GetLeakSpeed() string {
	if x != nil {
		return x.LeakSpeed
	}
	return ""
}

func (x *Alert) GetScenarioVersion() string {
	if x != nil {
		return x.ScenarioVersion
	}
	return ""
}

func (x *Alert) GetScenarioHash() string {
	if x != nil {
		return x.ScenarioHash
	}
	return ""
}

func (x *Alert) GetSimulated() bool {
	if x != nil {
		return x.Simulated
	}
	return false
}

func (x *Alert) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Alert) GetRemediation() bool {
	if x != nil {
		return x.Remediation
	}
	return false
}

func (x *Alert) GetMachineAlerts() int64 {
	if x != nil {
		return x.MachineAlerts
	}
	return 0
}

// DecisionBatch 决策批次
type DecisionBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Decision            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionBatch) Reset() {
	*x = DecisionBatch{}
	mi := &file_probe_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionBatch) ProtoMessage() {}

func (x *DecisionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionBatch.ProtoReflect.Descriptor instead.
func (*DecisionBatch) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{11}
}

func (x *DecisionBatch) GetItems() []*Decision {
	if x != nil {
		return x.Items
	}
	return nil
}

// HostActivityLogBatch 主机文件活动日志批次
type HostActivityLogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*HostActivityLog     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostActivityLogBatch) Reset() {
	*x = HostActivityLogBatch{}
	mi := &file_probe_sync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostActivityLogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostActivityLogBatch) ProtoMessage() {}

func (x *HostActivityLogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostActivityLogBatch.ProtoReflect.Descriptor instead.
func (*HostActivityLogBatch) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{12}
}

func (x *HostActivityLogBatch) GetItems() []*HostActivityLog {
	if x != nil {
		return x.Items
	}
	return nil
}

// HostActivityLog 主机文件活动日志结构
type HostActivityLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileName      string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Operation     string                 `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	User          string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	Process       string                 `protobuf:"bytes,7,opt,name=process,proto3" json:"process,omitempty"`
	Validation    string                 `protobuf:"bytes,8,opt,name=validation,proto3" json:"validation,omitempty"`
	IsFolder      int32                  `protobuf:"varint,9,opt,name=is_folder,json=isFolder,proto3" json:"is_folder,omitempty"`
	UploadedAt    string                 `protobuf:"bytes,10,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostActivityLog) Reset() {
	*x = HostActivityLog{}
	mi := &file_probe_sync_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostActivityLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostActivityLog) ProtoMessage() {}

func (x *HostActivityLog) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostActivityLog.ProtoReflect.Descriptor instead.
func (*HostActivityLog) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{13}
}

func (x *HostActivityLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HostActivityLog) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *HostActivityLog) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *HostActivityLog) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *HostActivityLog) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *HostActivityLog) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *HostActivityLog) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *HostActivityLog) GetValidation() string {
	if x != nil {
		return x.Validation
	}
	return ""
}

func (x *HostActivityLog) GetIsFolder() int32 {
	if x != nil {
		return x.IsFolder
	}
	return 0
}

func (x *HostActivityLog) GetUploadedAt() string {
	if x != nil {
		return x.UploadedAt
	}
	return ""
}

// HostProtectionLogBatch 主机文件保护日志批次
type HostProtectionLogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*HostProtectionLog   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostProtectionLogBatch) Reset() {
	*x = HostProtectionLogBatch{}
	mi := &file_probe_sync_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostProtectionLogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostProtectionLogBatch) ProtoMessage() {}

func (x *HostProtectionLogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostProtectionLogBatch.ProtoReflect.Descriptor instead.
func (*HostProtectionLogBatch) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{14}
}

func (x *HostProtectionLogBatch) GetItems() []*HostProtectionLog {
	if x != nil {
		return x.Items
	}
	return nil
}

// HostProtectionLog 主机文件保护日志结构
type HostProtectionLog struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp      string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FilePath       string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileName       string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Action         string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Success        int32                  `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	UnlockDuration int64                  `protobuf:"varint,7,opt,name=unlock_duration,json=unlockDuration,proto3" json:"unlock_duration,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	UploadedAt     string                 `protobuf:"bytes,9,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	RequestId      string                 `protobuf:"bytes,10,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HostProtectionLog) Reset() {
	*x = HostProtectionLog{}
	mi := &file_probe_sync_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostProtectionLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostProtectionLog) ProtoMessage() {}

func (x *HostProtectionLog) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostProtectionLog.ProtoReflect.Descriptor instead.
func (*HostProtectionLog) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{15}
}

func (x *HostProtectionLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HostProtectionLog) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *HostProtectionLog) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *HostProtectionLog) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *HostProtectionLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *HostProtectionLog) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *HostProtectionLog) GetUnlockDuration() int64 {
	if x != nil {
		return x.UnlockDuration
	}
	return 0
}

func (x *HostProtectionLog) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *HostProtectionLog) GetUploadedAt() string {
	if x != nil {
		return x.UploadedAt
	}
	return ""
}

func (x *HostProtectionLog) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Decision 决策结构
type Decision struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Until          string                 `protobuf:"bytes,4,opt,name=until,proto3" json:"until,omitempty"`
	Scenario       string                 `protobuf:"bytes,5,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Type           string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	StartIp        int64                  `protobuf:"varint,7,opt,name=start_ip,json=startIp,proto3" json:"start_ip,omitempty"`
	EndIp          int64                  `protobuf:"varint,8,opt,name=end_ip,json=endIp,proto3" json:"end_ip,omitempty"`
	StartSuffix    int64                  `protobuf:"varint,9,opt,name=start_suffix,json=startSuffix,proto3" json:"start_suffix,omitempty"`
	EndSuffix      int64                  `protobuf:"varint,10,opt,name=end_suffix,json=endSuffix,proto3" json:"end_suffix,omitempty"`
	IpSize         int64                  `protobuf:"varint,11,opt,name=ip_size,json=ipSize,proto3" json:"ip_size,omitempty"`
	Scope          string                 `protobuf:"bytes,12,opt,name=scope,proto3" json:"scope,omitempty"`
	Value          string                 `protobuf:"bytes,13,opt,name=value,proto3" json:"value,omitempty"`
	Origin         string                 `protobuf:"bytes,14,opt,name=origin,proto3" json:"origin,omitempty"`
	Simulated      bool                   `protobuf:"varint,15,opt,name=simulated,proto3" json:"simulated,omitempty"`
	Uuid           string                 `protobuf:"bytes,16,opt,name=uuid,proto3" json:"uuid,omitempty"`
	AlertDecisions int64                  `protobuf:"varint,17,opt,name=alert_decisions,json=alertDecisions,proto3" json:"alert_decisions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_probe_sync_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{16}
}

func (x *Decision) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Decision) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Decision) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Decision) GetUntil() string {
	if x != nil {
		return x.Until
	}
	return ""
}

func (x *Decision) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *Decision) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Decision) GetStartIp() int64 {
	if x != nil {
		return x.StartIp
	}
	return 0
}

func (x *Decision) GetEndIp() int64 {
	if x != nil {
		return x.EndIp
	}
	return 0
}

func (x *Decision) GetStartSuffix() int64 {
	if x != nil {
		return x.StartSuffix
	}
	return 0
}

func (x *Decision) GetEndSuffix() int64 {
	if x != nil {
		return x.EndSuffix
	}
	return 0
}

func (x *Decision) GetIpSize() int64 {
	if x != nil {
		return x.IpSize
	}
	return 0
}

func (x *Decision) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Decision) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Decision) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Decision) GetSimulated() bool {
	if x != nil {
		return x.Simulated
	}
	return false
}

func (x *Decision) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Decision) GetAlertDecisions() int64 {
	if x != nil {
		return x.AlertDecisions
	}
	return 0
}

// CommandAck 指令执行确认
type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        CommandStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=probesync.CommandStatus" json:"status,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // JSON 编码的结果
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_probe_sync_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{17}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_COMMAND_STATUS_UNSPECIFIED
}

func (x *CommandAck) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CommandAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// BackendMessage 后端发送的消息
type BackendMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BackendMessage_HeartbeatAck
	//	*BackendMessage_BatchAck
	//	*BackendMessage_Command
	//	*BackendMessage_ConfigUpdate
	Payload       isBackendMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendMessage) Reset() {
	*x = BackendMessage{}
	mi := &file_probe_sync_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendMessage) ProtoMessage() {}

func (x *BackendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendMessage.ProtoReflect.Descriptor instead.
func (*BackendMessage) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{18}
}

func (x *BackendMessage) GetPayload() isBackendMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BackendMessage) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*BackendMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *BackendMessage) GetBatchAck() *BatchAck {
	if x != nil {
		if x, ok := x.Payload.(*BackendMessage_BatchAck); ok {
			return x.BatchAck
		}
	}
	return nil
}

func (x *BackendMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*BackendMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *BackendMessage) GetConfigUpdate() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Payload.(*BackendMessage_ConfigUpdate); ok {
			return x.ConfigUpdate
		}
	}
	return nil
}

type isBackendMessage_Payload interface {
	isBackendMessage_Payload()
}

type BackendMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,10,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type BackendMessage_BatchAck struct {
	BatchAck *BatchAck `protobuf:"bytes,11,opt,name=batch_ack,json=batchAck,proto3,oneof"`
}

type BackendMessage_Command struct {
	Command *Command `protobuf:"bytes,12,opt,name=command,proto3,oneof"`
}

type BackendMessage_ConfigUpdate struct {
	ConfigUpdate *ConfigUpdate `protobuf:"bytes,13,opt,name=config_update,json=configUpdate,proto3,oneof"`
}

func (*BackendMessage_HeartbeatAck) isBackendMessage_Payload() {}

func (*BackendMessage_BatchAck) isBackendMessage_Payload() {}

func (*BackendMessage_Command) isBackendMessage_Payload() {}

func (*BackendMessage_ConfigUpdate) isBackendMessage_Payload() {}

// HeartbeatAck 心跳响应
type HeartbeatAck struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ServerTime            string                 `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	ConfigUpdateAvailable bool                   `protobuf:"varint,2,opt,name=config_update_available,json=configUpdateAvailable,proto3" json:"config_update_available,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_probe_sync_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{19}
}

func (x *HeartbeatAck) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

func (x *HeartbeatAck) GetConfigUpdateAvailable() bool {
	if x != nil {
		return x.ConfigUpdateAvailable
	}
	return false
}

// BatchAck 批次确认
type BatchAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Status        AckStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=probesync.AckStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAck) Reset() {
	*x = BatchAck{}
	mi := &file_probe_sync_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAck) ProtoMessage() {}

func (x *BatchAck) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAck.ProtoReflect.Descriptor instead.
func (*BatchAck) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{20}
}

func (x *BatchAck) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchAck) GetStatus() AckStatus {
	if x != nil {
		return x.Status
	}
	return AckStatus_ACK_STATUS_UNSPECIFIED
}

func (x *BatchAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Command 指令消息
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=probesync.CommandType" json:"type,omitempty"`
	Params        []byte                 `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"` // JSON 编码的参数
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_probe_sync_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{21}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return COMMAND_TYPE_UNSPECIFIED
}

func (x *Command) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Command) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Command) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

// ConfigUpdate 配置更新
type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Config        []byte                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"` // YAML 配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_probe_sync_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_probe_sync_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_probe_sync_proto_rawDescGZIP(), []int{22}
}

func (x *ConfigUpdate) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigUpdate) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_probe_sync_proto protoreflect.FileDescriptor

const file_probe_sync_proto_rawDesc = "" +
	"\n" +
	"\x10probe_sync.proto\x12\tprobesync\"\xdb\x01\n" +
	"\fProbeMessage\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\tR\aprobeId\x124\n" +
	"\theartbeat\x18\n" +
	" \x01(\v2\x14.probesync.HeartbeatH\x00R\theartbeat\x125\n" +
	"\n" +
	"data_batch\x18\v \x01(\v2\x14.probesync.DataBatchH\x00R\tdataBatch\x128\n" +
	"\vcommand_ack\x18\f \x01(\v2\x15.probesync.CommandAckH\x00R\n" +
	"commandAckB\t\n" +
	"\apayload\"Y\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12.\n" +
	"\x06status\x18\x02 \x01(\v2\x16.probesync.ProbeStatusR\x06status\"\xfe\x01\n" +
	"\vProbeStatus\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12.\n" +
	"\x13pending_access_logs\x18\x03 \x01(\x03R\x11pendingAccessLogs\x12%\n" +
	"\x0epending_alerts\x18\x04 \x01(\x03R\rpendingAlerts\x12+\n" +
	"\x11pending_decisions\x18\x05 \x01(\x03R\x10pendingDecisions\x12*\n" +
	"\x11pending_host_logs\x18\x06 \x01(\x03R\x0fpendingHostLogs\"\xdb\x03\n" +
	"\tDataBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x1f\n" +
	"\vcursor_from\x18\x04 \x01(\x03R\n" +
	"cursorFrom\x12\x1b\n" +
	"\tcursor_to\x18\x05 \x01(\x03R\bcursorTo\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\x129\n" +
	"\n" +
	"caddy_logs\x18\n" +
	" \x01(\v2\x18.probesync.CaddyLogBatchH\x00R\tcaddyLogs\x12/\n" +
	"\x06alerts\x18\v \x01(\v2\x15.probesync.AlertBatchH\x00R\x06alerts\x128\n" +
	"\tdecisions\x18\f \x01(\v2\x18.probesync.DecisionBatchH\x00R\tdecisions\x12O\n" +
	"\x12host_activity_logs\x18\r \x01(\v2\x1f.probesync.HostActivityLogBatchH\x00R\x10hostActivityLogs\x12U\n" +
	"\x14host_protection_logs\x18\x0e \x01(\v2!.probesync.HostProtectionLogBatchH\x00R\x12hostProtectionLogsB\t\n" +
	"\apayload\":\n" +
	"\rCaddyLogBatch\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.probesync.CaddyLogR\x05items\"\xad\x03\n" +
	"\bCaddyLog\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x01R\x02ts\x12\x16\n" +
	"\x06logger\x18\x03 \x01(\tR\x06logger\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x121\n" +
	"\arequest\x18\x05 \x01(\v2\x17.probesync.CaddyRequestR\arequest\x12\x1d\n" +
	"\n" +
	"bytes_read\x18\x06 \x01(\x03R\tbytesRead\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x12\x1a\n" +
	"\bduration\x18\b \x01(\x01R\bduration\x12\x12\n" +
	"\x04size\x18\t \x01(\x03R\x04size\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\rR\x06status\x12G\n" +
	"\fresp_headers\x18\v \x03(\v2$.probesync.CaddyLog.RespHeadersEntryR\vrespHeaders\x1aU\n" +
	"\x10RespHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.probesync.StringListR\x05value:\x028\x01\"\xf7\x02\n" +
	"\fCaddyRequest\x12\x1b\n" +
	"\tremote_ip\x18\x01 \x01(\tR\bremoteIp\x12\x1f\n" +
	"\vremote_port\x18\x02 \x01(\tR\n" +
	"remotePort\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\x12\x14\n" +
	"\x05proto\x18\x04 \x01(\tR\x05proto\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x12\n" +
	"\x04host\x18\x06 \x01(\tR\x04host\x12\x10\n" +
	"\x03uri\x18\a \x01(\tR\x03uri\x12>\n" +
	"\aheaders\x18\b \x03(\v2$.probesync.CaddyRequest.HeadersEntryR\aheaders\x12%\n" +
	"\x03tls\x18\t \x01(\v2\x13.probesync.CaddyTlsR\x03tls\x1aQ\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.probesync.StringListR\x05value:\x028\x01\"\x98\x01\n" +
	"\bCaddyTls\x12\x18\n" +
	"\aresumed\x18\x01 \x01(\bR\aresumed\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12!\n" +
	"\fcipher_suite\x18\x03 \x01(\rR\vcipherSuite\x12\x14\n" +
	"\x05proto\x18\x04 \x01(\tR\x05proto\x12\x1f\n" +
	"\vserver_name\x18\x05 \x01(\tR\n" +
	"serverName\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"4\n" +
	"\n" +
	"AlertBatch\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.probesync.AlertR\x05items\"\xe0\x06\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x1a\n" +
	"\bscenario\x18\x04 \x01(\tR\bscenario\x12\x1b\n" +
	"\tbucket_id\x18\x05 \x01(\tR\bbucketId\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12!\n" +
	"\fevents_count\x18\a \x01(\x05R\veventsCount\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\tR\tstartedAt\x12\x1d\n" +
	"\n" +
	"stopped_at\x18\t \x01(\tR\tstoppedAt\x12\x1b\n" +
	"\tsource_ip\x18\n" +
	" \x01(\tR\bsourceIp\x12!\n" +
	"\fsource_range\x18\v \x01(\tR\vsourceRange\x12(\n" +
	"\x10source_as_number\x18\f \x01(\tR\x0esourceAsNumber\x12$\n" +
	"\x0esource_as_name\x18\r \x01(\tR\fsourceAsName\x12%\n" +
	"\x0esource_country\x18\x0e \x01(\tR\rsourceCountry\x12'\n" +
	"\x0fsource_latitude\x18\x0f \x01(\x01R\x0esourceLatitude\x12)\n" +
	"\x10source_longitude\x18\x10 \x01(\x01R\x0fsourceLongitude\x12!\n" +
	"\fsource_scope\x18\x11 \x01(\tR\vsourceScope\x12!\n" +
	"\fsource_value\x18\x12 \x01(\tR\vsourceValue\x12\x1a\n" +
	"\bcapacity\x18\x13 \x01(\x05R\bcapacity\x12\x1d\n" +
	"\n" +
	"leak_speed\x18\x14 \x01(\tR\tleakSpeed\x12)\n" +
	"\x10scenario_version\x18\x15 \x01(\tR\x0fscenarioVersion\x12#\n" +
	"\rscenario_hash\x18\x16 \x01(\tR\fscenarioHash\x12\x1c\n" +
	"\tsimulated\x18\x17 \x01(\bR\tsimulated\x12\x12\n" +
	"\x04uuid\x18\x18 \x01(\tR\x04uuid\x12 \n" +
	"\vremediation\x18\x19 \x01(\bR\vremediation\x12%\n" +
	"\x0emachine_alerts\x18\x1a \x01(\x03R\rmachineAlerts\":\n" +
	"\rDecisionBatch\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.probesync.DecisionR\x05items\"H\n" +
	"\x14HostActivityLogBatch\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.probesync.HostActivityLogR\x05items\"\xa3\x02\n" +
	"\x0fHostActivityLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12\x18\n" +
	"\aprocess\x18\a \x01(\tR\aprocess\x12\x1e\n" +
	"\n" +
	"validation\x18\b \x01(\tR\n" +
	"validation\x12\x1b\n" +
	"\tis_folder\x18\t \x01(\x05R\bisFolder\x12\x1f\n" +
	"\vuploaded_at\x18\n" +
	" \x01(\tR\n" +
	"uploadedAt\"L\n" +
	"\x16HostProtectionLogBatch\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.probesync.HostProtectionLogR\x05items\"\xbb\x02\n" +
	"\x11HostProtectionLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\x05R\asuccess\x12'\n" +
	"\x0funlock_duration\x18\a \x01(\x03R\x0eunlockDuration\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vuploaded_at\x18\t \x01(\tR\n" +
	"uploadedAt\x12\x1d\n" +
	"\n" +
	"request_id\x18\n" +
	" \x01(\tR\trequestId\"\xca\x03\n" +
	"\bDecision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x14\n" +
	"\x05until\x18\x04 \x01(\tR\x05until\x12\x1a\n" +
	"\bscenario\x18\x05 \x01(\tR\bscenario\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x19\n" +
	"\bstart_ip\x18\a \x01(\x03R\astartIp\x12\x15\n" +
	"\x06end_ip\x18\b \x01(\x03R\x05endIp\x12!\n" +
	"\fstart_suffix\x18\t \x01(\x03R\vstartSuffix\x12\x1d\n" +
	"\n" +
	"end_suffix\x18\n" +
	" \x01(\x03R\tendSuffix\x12\x17\n" +
	"\aip_size\x18\v \x01(\x03R\x06ipSize\x12\x14\n" +
	"\x05scope\x18\f \x01(\tR\x05scope\x12\x14\n" +
	"\x05value\x18\r \x01(\tR\x05value\x12\x16\n" +
	"\x06origin\x18\x0e \x01(\tR\x06origin\x12\x1c\n" +
	"\tsimulated\x18\x0f \x01(\bR\tsimulated\x12\x12\n" +
	"\x04uuid\x18\x10 \x01(\tR\x04uuid\x12'\n" +
	"\x0falert_decisions\x18\x11 \x01(\x03R\x0ealertDecisions\"\x8b\x01\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.probesync.CommandStatusR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xff\x01\n" +
	"\x0eBackendMessage\x12>\n" +
	"\rheartbeat_ack\x18\n" +
	" \x01(\v2\x17.probesync.HeartbeatAckH\x00R\fheartbeatAck\x122\n" +
	"\tbatch_ack\x18\v \x01(\v2\x13.probesync.BatchAckH\x00R\bbatchAck\x12.\n" +
	"\acommand\x18\f \x01(\v2\x12.probesync.CommandH\x00R\acommand\x12>\n" +
	"\rconfig_update\x18\r \x01(\v2\x17.probesync.ConfigUpdateH\x00R\fconfigUpdateB\t\n" +
	"\apayload\"g\n" +
	"\fHeartbeatAck\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\tR\n" +
	"serverTime\x126\n" +
	"\x17config_update_available\x18\x02 \x01(\bR\x15configUpdateAvailable\"i\n" +
	"\bBatchAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.probesync.AckStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x9b\x01\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.probesync.CommandTypeR\x04type\x12\x16\n" +
	"\x06params\x18\x03 \x01(\fR\x06params\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\tR\texpiresAt\"@\n" +
	"\fConfigUpdate\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06config\x18\x02 \x01(\fR\x06config*f\n" +
	"\rCommandStatus\x12\x1e\n" +
	"\x1aCOMMAND_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16COMMAND_STATUS_SUCCESS\x10\x01\x12\x19\n" +
	"\x15COMMAND_STATUS_FAILED\x10\x02*j\n" +
	"\tAckStatus\x12\x1a\n" +
	"\x16ACK_STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACK_STATUS_OK\x10\x01\x12\x18\n" +
	"\x14ACK_STATUS_DUPLICATE\x10\x02\x12\x14\n" +
	"\x10ACK_STATUS_ERROR\x10\x03*\xbc\x03\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11COMMAND_TYPE_PING\x10\x01\x12\x1b\n" +
	"\x17COMMAND_TYPE_FORCE_SYNC\x10\x02\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_ADD_WHITELIST\x10\x03\x12!\n" +
	"\x1dCOMMAND_TYPE_REMOVE_WHITELIST\x10\x04\x12\x1d\n" +
	"\x19COMMAND_TYPE_ADD_DECISION\x10\x05\x12 \n" +
	"\x1cCOMMAND_TYPE_REMOVE_DECISION\x10\x06\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_UPDATE_CONFIG\x10\a\x12\x1f\n" +
	"\x1bCOMMAND_TYPE_HOST_LOCK_PATH\x10\b\x12&\n" +
	"\"COMMAND_TYPE_HOST_TEMP_UNLOCK_PATH\x10\t\x12&\n" +
	"\"COMMAND_TYPE_HOST_EMERGENCY_UNLOCK\x10\n" +
	"\x12\"\n" +
	"\x1eCOMMAND_TYPE_HOST_QUERY_STATUS\x10\v\x12\"\n" +
	"\x1eCOMMAND_TYPE_HOST_APPLY_POLICY\x10\f2N\n" +
	"\tProbeSync\x12A\n" +
	"\aConnect\x12\x17.probesync.ProbeMessage\x1a\x19.probesync.BackendMessage(\x010\x01B4Z2github.com/crowdsecurity/crowdsec/pkg/probesync/pbb\x06proto3"

var (
	file_probe_sync_proto_rawDescOnce sync.Once
	file_probe_sync_proto_rawDescData []byte
)

func file_probe_sync_proto_rawDescGZIP() []byte {
	file_probe_sync_proto_rawDescOnce.Do(func() {
		file_probe_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_probe_sync_proto_rawDesc), len(file_probe_sync_proto_rawDesc)))
	})
	return file_probe_sync_proto_rawDescData
}

var file_probe_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_probe_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_probe_sync_proto_goTypes = []any{
	(CommandStatus)(0),             // 0: probesync.CommandStatus
	(AckStatus)(0),                 // 1: probesync.AckStatus
	(CommandType)(0),               // 2: probesync.CommandType
	(*ProbeMessage)(nil),           // 3: probesync.ProbeMessage
	(*Heartbeat)(nil),              // 4: probesync.Heartbeat
	(*ProbeStatus)(nil),            // 5: probesync.ProbeStatus
	(*DataBatch)(nil),              // 6: probesync.DataBatch
	(*CaddyLogBatch)(nil),          // 7: probesync.CaddyLogBatch
	(*CaddyLog)(nil),               // 8: probesync.CaddyLog
	(*CaddyRequest)(nil),           // 9: probesync.CaddyRequest
	(*CaddyTls)(nil),               // 10: probesync.CaddyTls
	(*StringList)(nil),             // 11: probesync.StringList
	(*AlertBatch)(nil),             // 12: probesync.AlertBatch
	(*Alert)(nil),                  // 13: probesync.Alert
	(*DecisionBatch)(nil),          // 14: probesync.DecisionBatch
	(*HostActivityLogBatch)(nil),   // 15: probesync.HostActivityLogBatch
	(*HostActivityLog)(nil),        // 16: probesync.HostActivityLog
	(*HostProtectionLogBatch)(nil), // 17: probesync.HostProtectionLogBatch
	(*HostProtectionLog)(nil),      // 18: probesync.HostProtectionLog
	(*Decision)(nil),               // 19: probesync.Decision
	(*CommandAck)(nil),             // 20: probesync.CommandAck
	(*BackendMessage)(nil),         // 21: probesync.BackendMessage
	(*HeartbeatAck)(nil),           // 22: probesync.HeartbeatAck
	(*BatchAck)(nil),               // 23: probesync.BatchAck
	(*Command)(nil),                // 24: probesync.Command
	(*ConfigUpdate)(nil),           // 25: probesync.ConfigUpdate
	nil,                            // 26: probesync.CaddyLog.RespHeadersEntry
	nil,                            // 27: probesync.CaddyRequest.HeadersEntry
}
var file_probe_sync_proto_depIdxs = []int32{
	4,  // 0: probesync.ProbeMessage.heartbeat:type_name -> probesync.Heartbeat
	6,  // 1: probesync.ProbeMessage.data_batch:type_name -> probesync.DataBatch
	20, // 2: probesync.ProbeMessage.command_ack:type_name -> probesync.CommandAck
	5,  // 3: probesync.Heartbeat.status:type_name -> probesync.ProbeStatus
	7,  // 4: probesync.DataBatch.caddy_logs:type_name -> probesync.CaddyLogBatch
	12, // 5: probesync.DataBatch.alerts:type_name -> probesync.AlertBatch
	14, // 6: probesync.DataBatch.decisions:type_name -> probesync.DecisionBatch
	15, // 7: probesync.DataBatch.host_activity_logs:type_name -> probesync.HostActivityLogBatch
	17, // 8: probesync.DataBatch.host_protection_logs:type_name -> probesync.HostProtectionLogBatch
	8,  // 9: probesync.CaddyLogBatch.items:type_name -> probesync.CaddyLog
	9,  // 10: probesync.CaddyLog.request:type_name -> probesync.CaddyRequest
	26, // 11: probesync.CaddyLog.resp_headers:type_name -> probesync.CaddyLog.RespHeadersEntry
	27, // 12: probesync.CaddyRequest.headers:type_name -> probesync.CaddyRequest.HeadersEntry
	10, // 13: probesync.CaddyRequest.tls:type_name -> probesync.CaddyTls
	13, // 14: probesync.AlertBatch.items:type_name -> probesync.Alert
	19, // 15: probesync.DecisionBatch.items:type_name -> probesync.Decision
	16, // 16: probesync.HostActivityLogBatch.items:type_name -> probesync.HostActivityLog
	18, // 17: probesync.HostProtectionLogBatch.items:type_name -> probesync.HostProtectionLog
	0,  // 18: probesync.CommandAck.status:type_name -> probesync.CommandStatus
	22, // 19: probesync.BackendMessage.heartbeat_ack:type_name -> probesync.HeartbeatAck
	23, // 20: probesync.BackendMessage.batch_ack:type_name -> probesync.BatchAck
	24, // 21: probesync.BackendMessage.command:type_name -> probesync.Command
	25, // 22: probesync.BackendMessage.config_update:type_name -> probesync.ConfigUpdate
	1,  // 23: probesync.BatchAck.status:type_name -> probesync.AckStatus
	2,  // 24: probesync.Command.type:type_name -> probesync.CommandType
	11, // 25: probesync.CaddyLog.RespHeadersEntry.value:type_name -> probesync.StringList
	11, // 26: probesync.CaddyRequest.HeadersEntry.value:type_name -> probesync.StringList
	3,  // 27: probesync.ProbeSync.Connect:input_type -> probesync.ProbeMessage
	21, // 28: probesync.ProbeSync.Connect:output_type -> probesync.BackendMessage
	28, // [28:29] is the sub-list for method output_type
	27, // [27:28] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_probe_sync_proto_init() }
func file_probe_sync_proto_init() {
	if File_probe_sync_proto != nil {
		return
	}
	file_probe_sync_proto_msgTypes[0].OneofWrappers = []any{
		(*ProbeMessage_Heartbeat)(nil),
		(*ProbeMessage_DataBatch)(nil),
		(*ProbeMessage_CommandAck)(nil),
	}
	file_probe_sync_proto_msgTypes[3].OneofWrappers = []any{
		(*DataBatch_CaddyLogs)(nil),
		(*DataBatch_Alerts)(nil),
		(*DataBatch_Decisions)(nil),
		(*DataBatch_HostActivityLogs)(nil),
		(*DataBatch_HostProtectionLogs)(nil),
	}
	file_probe_sync_proto_msgTypes[18].OneofWrappers = []any{
		(*BackendMessage_HeartbeatAck)(nil),
		(*BackendMessage_BatchAck)(nil),
		(*BackendMessage_Command)(nil),
		(*BackendMessage_ConfigUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_probe_sync_proto_rawDesc), len(file_probe_sync_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_probe_sync_proto_goTypes,
		DependencyIndexes: file_probe_sync_proto_depIdxs,
		EnumInfos:         file_probe_sync_proto_enumTypes,
		MessageInfos:      file_probe_sync_proto_msgTypes,
	}.Build()
	File_probe_sync_proto = out.File
	file_probe_sync_proto_goTypes = nil
	file_probe_sync_proto_depIdxs = nil
}
