// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.4
// source: probe_sync.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProbeSync_Connect_FullMethodName = "/probesync.ProbeSync/Connect"
)

// ProbeSyncClient is the client API for ProbeSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProbeSync 探针同步服务 - 双向流通信
type ProbeSyncClient interface {
	// Connect 双向流：探针发起连接，保持长连接
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProbeMessage, BackendMessage], error)
}

type probeSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewProbeSyncClient(cc grpc.ClientConnInterface) ProbeSyncClient {
	return &probeSyncClient{cc}
}

func (c *probeSyncClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProbeMessage, BackendMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProbeSync_ServiceDesc.Streams[0], ProbeSync_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProbeMessage, BackendMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProbeSync_ConnectClient = grpc.BidiStreamingClient[ProbeMessage, BackendMessage]

// ProbeSyncServer is the server API for ProbeSync service.
// All implementations must embed UnimplementedProbeSyncServer
// for forward compatibility.
//
// ProbeSync 探针同步服务 - 双向流通信
type ProbeSyncServer interface {
	// Connect 双向流：探针发起连接，保持长连接
	Connect(grpc.BidiStreamingServer[ProbeMessage, BackendMessage]) error
	mustEmbedUnimplementedProbeSyncServer()
}

// UnimplementedProbeSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProbeSyncServer struct{}

func (UnimplementedProbeSyncServer) Connect(grpc.BidiStreamingServer[ProbeMessage, BackendMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedProbeSyncServer) mustEmbedUnimplementedProbeSyncServer() {}
func (UnimplementedProbeSyncServer) testEmbeddedByValue()                   {}

// UnsafeProbeSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProbeSyncServer will
// result in compilation errors.
type UnsafeProbeSyncServer interface {
	mustEmbedUnimplementedProbeSyncServer()
}

func RegisterProbeSyncServer(s grpc.ServiceRegistrar, srv ProbeSyncServer) {
	// If the following call panics, it indicates UnimplementedProbeSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProbeSync_ServiceDesc, srv)
}

func _ProbeSync_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProbeSyncServer).Connect(&grpc.GenericServerStream[ProbeMessage, BackendMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProbeSync_ConnectServer = grpc.BidiStreamingServer[ProbeMessage, BackendMessage]

// ProbeSync_ServiceDesc is the grpc.ServiceDesc for ProbeSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProbeSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "probesync.ProbeSync",
	HandlerType: (*ProbeSyncServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ProbeSync_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "probe_sync.proto",
}
